# Crie um pipeline do GitHub Actions que execute quando um Pull Request for criado
# e crie o seguinte comentario: "Obrigado pela sua alteração"

name: Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  pull_request:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Obrigado pela sua alteração'
            })