# Crie um pipeline no GItHub Actions que execute de forma agendada
# a execução deve ocorrer a cada 1 minuto
# escreva na tela "Olá, mundo!"

name: Agendamento

on:
  schedule:
  #altere o cron para rodar a cada 5 minutos
    - cron: '*/5 * * * *'
#    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Olá, mundo!"
